apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micro-test
  template:
    metadata:
      labels:
        app: micro-test
    spec:
      containers:
      - name: micro-test
        image: gcr.io/smartleep-app/micro-test
        imagePullPolicy: Always
