apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-test
  template:
    metadata:
      labels:
        app: micro-test
    spec:
      containers:
      - name: micro-test
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID.
        image: us-west1-docker.pkg.dev/smartleep-app/repo-smartleep/helloworld-gke:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
