apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    minReadySeconds: 5
  template:
    metadata:
      labels:
        app: micro-test
    spec:
      containers:
      - name: micro-test
        image: "gcr.io/smartleep-app/test-deploy:latest"
