apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testApp
  name: micro-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micro-test
  template:
    metadata:
      labels:
        app: micro-test
   spec:
     containers:
       - image: gcr.io/smartleep-app/micro-test
       imagePullPolicy: IfNotPresent
       name: micro-test
    dnsPolicy: ClusterFirst
    restartPolicy: Always
